name: Build and Test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ "11.0.21+9", "17.0.9+9", "21" ]

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          # https://github.com/diffplug/spotless/issues/1242
          fetch-depth: 0

      - name: Set up Azul Zulu OpenJDK Using Matrix
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "zulu"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Download or get from cache Sudachi dictionary
        id: download-and-cache-sudachi-dictionary
        uses: ./.github/actions/download-and-cache-sudachi-dictionary

      - name: Build
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew clean test
  
  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
